### ISSUE TITLE
Use battery data in Energy dashboard

### ISSUE THREAD

**Issue by rploeg** [WillCodeForCats/solaredge-modbus-multi#113]
Hi,

I receive import and export kWh data from my LG battery via this integration, but I can't select that yet in the Energy dashboard (think because it is not long term statistics entities):

![2022-09-30_16-54-11](https://user-images.githubusercontent.com/49752333/193297855-d9fda18b-7402-4105-9b7c-52cf0019e0c8.png)

Would it be possible to use those energy import and export sensor from a battery in the energy dashboard?

**Comment by WillCodeForCats** [comment]
It works on my test system:

<img width="442" alt="Screen Shot 2022-09-30 at 8 48 20 AM" src="https://user-images.githubusercontent.com/48533968/193308330-c9433a11-6e22-48a3-bd89-6bb3375ad21b.png">

**Comment by rploeg** [comment]
Strange, I don't see it, only the ones for the solaredge API integration:

<img width="500" alt="2022-09-30_18-39-01" src="https://user-images.githubusercontent.com/49752333/193317240-e85e635c-fffe-4f2a-8578-3fd8ca199158.png">

And see the two fields also in the statistics of HA:

<img width="1089" alt="2022-09-30_18-39-54" src="https://user-images.githubusercontent.com/49752333/193317348-f6e129a4-4c34-4be8-8afd-d7820fc67f56.png">

**Comment by rploeg** [comment]
Reboot of HA did the trick
