### ISSUE TITLE
Updating state took X seconds

### ISSUE THREAD

**Issue by WillCodeForCats** [WillCodeForCats/solaredge-modbus-multi#155]
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:545
First occurred: 4:37:46 AM (2 occurrences)
Last logged: 7:31:35 AM

Updating state for sensor.solaredge_m1_imported_a_kwh (<class 'custom_components.solaredge_modbus_multi.sensor.ACEnergy'>) took 0.658 seconds. Please report it to the custom integration author.
Updating state for sensor.washing_machine_today_s_consumption (<class 'homeassistant.components.tplink.sensor.SmartPlugSensor'>) took 0.672 seconds. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+tplink%22
```

_Originally posted by @purcell-lab in https://github.com/WillCodeForCats/solaredge-modbus-multi/issues/137#issuecomment-1296406664_

**Comment by WillCodeForCats** [comment]
Have not been able to observe or duplicate this yet.

**Comment by WillCodeForCats** [comment]
Closing since it hasn't been observed since opening issue.

**Comment by wendels** [comment]
@WillCodeForCats 

Not the same sensor, but just got the same issue:

Log details (WARNING)
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1214
First occurred: 11:30:27 AM (1 occurrence)
Last logged: 11:30:27 AM

Updating state for sensor.solaredge_i1_m1_ac_power_a (<class 'custom_components.solaredge_modbus_multi.sensor.ACPower'>) took 0.823 seconds. Please create a bug report at https://github.com/WillCodeForCats/solaredge-modbus-multi/issues

Also haven't seen it before today either, but only been running homeassistant with solaredge for about 2 months.
