### ISSUE TITLE
Battery lifetime import and export values

### ISSUE THREAD

**Issue by djfanatix** [WillCodeForCats/solaredge-modbus-multi#185]
**Describe the current behavior**
A clear and concise description of what the feature should be.

**What should be updated or changed?**
Could you check these values:
-solaredge_b1_energy_import
-solaredge_b1_energy_export.

I think these are lifetime accumulating values, but I have jumping values

![image](https://user-images.githubusercontent.com/43752712/201420088-b1befa44-fc3d-4b6d-ac9b-1e967c5e7217.jpeg)

**Home Assistant (please complete the following information):**
 - Home Assistant Core Version: 2022.11 
 - solaredge-modbus-multi Version:
2.2.7 b7

**Additional context**
Add any other context about the request here.
![image](https://user-images.githubusercontent.com/43752712/201420144-6b0650dd-bb57-411f-aefc-5d3092ec5197.jpeg)

**Comment by WillCodeForCats** [comment]
This is a known issue with some hardware:

https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Known-Issues
