### ISSUE TITLE
Plugin Configuration is not possible

### ISSUE THREAD

**Issue by dominikamann** [WillCodeForCats/solaredge-modbus-multi#214]
**Describe the bug**
Hi,

i installed the integration by HACS (latest Version) and tried to configure the integration. I always running into the following issue.

1.) Select integration
![grafik](https://user-images.githubusercontent.com/29973737/208890212-e10b7460-5db3-48a2-be1d-5164db1ace0e.png)

2.)
![grafik](https://user-images.githubusercontent.com/29973737/208890309-00bb8d3f-e9c1-449c-9cb5-1c96208d3e34.png)

I tried several restarts and different versions. 

Thank you!

**Expected behavior**
Configuration dialog will open.

**Home Assistant (please complete the following information):**
 - Home Assistant Core Version: Home Assistant 2022.12.7 Supervisor 2022.11.2 Operating System 9.4 Frontend 20221213.1 - latest 
 - solaredge-modbus-multi Version: v2.2.7

**Comment by dominikamann** [comment]
If found the following log:
`
 Logger: homeassistant.config_entries
Source: config_entries.py:834
First occurred: 12:00:15 (2 occurrences)
Last logged: 12:02:31
Error occurred loading configuration flow for integration solaredge_modbus_multi: cannot import name 'ModbusTcpClient' from 'pymodbus.client' (/usr/local/lib/python3.10/site-packages/pymodbus/client/__init__.py)`

**Comment by dominikamann** [comment]
Duplicate of https://github.com/WillCodeForCats/solaredge-modbus-multi/issues/162

**Comment by WillCodeForCats** [comment]
Install pymodbus 3.0.1 or newer.
