### ISSUE TITLE
Config-flow kon niet geladen worden: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by sbeukers** [WillCodeForCats/solaredge-modbus-multi#227]
When I download the integration from HACS all is well. but when i add it to my integrations I get:
"Config-flow kon niet geladen worden: {"message":"Invalid handler specified"}"

![image](https://user-images.githubusercontent.com/65311410/212177208-0b5f65ad-89d7-47fa-bb44-13dbfc5ac39d.png)

Can you help me with this problem?
If you need anything let me know

**Comment by WillCodeForCats** [comment]
Please use the bug report template to submit issues.

**Comment by sbeukers** [comment]
What did I do wrong? Don't you want this bug fixed? I followed the bug report template.. to my best understanding.
Can you please tell me what you expect more?

**Comment by WillCodeForCats** [comment]
I don't see the template. None of the questions it asks were answered. The template exists so I don't have to go back and forth asking questions and waiting for answers for things that should be filled out in the first post. This issue has no logs, no versions, and no information for me to work with.

**Comment by sbeukers** [comment]
I wasn't the first I see. 
https://github.com/WillCodeForCats/solaredge-modbus-multi/issues/214
https://github.com/WillCodeForCats/solaredge-modbus-multi/issues/162
thanks

**Comment by WillCodeForCats** [comment]
Yes, that problem has a specific log message (which is why the template asks for logs).

Unfortunately there is no fix until HA core catches up with a newer version of pymodbus, or you don't use any other integrations that rely on versions of pymodbus older than 3.0.0. The maintainer is aware of the problem but has not given any timeline for their work to get an updated version into Home Assistant core.

**Comment by sbeukers** [comment]
Thanks for your time anyway. The solution was to just install 2.2.5

**Comment by WillCodeForCats** [comment]
Yes until Home Assistant gets the update, the last version that will work with old versions of the pymodbus module is release v2.2.5
