### ISSUE TITLE
3 inverters not detected - only 2

### ISSUE THREAD

**Issue by jiripaskov** [WillCodeForCats/solaredge-modbus-multi#258]
Before reporting a bug, make sure your configuration is correct, your LAN is working, and you have read about the "Known Issues" in the wiki:
https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki

**Describe the bug**
Have latest HASSio with your addon. Have SE33.3 as master and two SE50 as slaves. Everything runs well if I will config 2 inverters. I can get data from 2 inverters. But if I configure 3 inverters (which is true) I will get error - no response from inverter ID 3. I think there could be problem that inverters ID are not 1,2,3 but maybe different? Not sure exactly...

**Expected behavior**
Addon should detect 3 inverters.

**Screenshots**
If applicable, add screenshots of the problem and/or configuration.

**Logs**
Inverter device ID 3: No response from inverter ID 3
19:46:39 – (CHYBA) SolarEdge Modbus Multi Device
Config entry 'SolarEdge' for solaredge_modbus_multi integration not ready yet: No response from inverter ID 3; Retrying in background
19:45:49 – (VAROVÁNÍ) config_entries.py

**Debug Logs**
Debug logs are not always necessary, but may be required for more complex issues. You can enable debug logs by adding the following to your `configuration.yaml` file and restarting Home Assistant.
```
logger:
    default: warning
    logs:
        custom_components.solaredge_modbus_multi: debug
```
Debug logging will generate a large amount of data: it is recommended to configure it, collect the data needed, then remove debug logging during normal operation.

**Home Assistant (please complete the following information):**
 - Home Assistant Core Version:
 - solaredge-modbus-multi Version:

**Additional context**

**Comment by WillCodeForCats** [comment]
If you aren't sure if your inverters are set up correctly, read the instructions. Don't open issues for setup help.
