### ISSUE TITLE
Enhancement request: Reconfigure integration via UI

### ISSUE THREAD

**Issue by Benny-Git** [WillCodeForCats/solaredge-modbus-multi#26]
**Describe the ~bug~ enhancement request**
I set up the integration and like it. However I wanted to now lower the scan interval, and could not do so via the UI, though the setup worked fine via the UI.

**Expected behavior**
The UI config should allow me to make changes to the existing integration config.

**Screenshots**
n/a

**Logs**
n/a

**Home Assistant (please complete the following information):**
 - Version: 2022.4.7

**Additional context**
I could change the scan_interval by editing my .storage/core.config_entries, but this is not as comfortable as using a config UI.

**Comment by WillCodeForCats** [comment]
Home Assistant unfortunately doesn't support editing or updating configuration in the UI, but I could move poll interval to the "options" side which shows up when you click the "configure" button for the integration.

Here's the bug in HA: https://github.com/home-assistant/architecture/issues/377 (Ability to edit/update config entries)

**Comment by Benny-Git** [comment]
Interesting. I know the "configure" button on some of my integrations, but didn’t know it was very distinct from the initial config.
So moving this to the options means a whole lot of rework?

**Comment by WillCodeForCats** [comment]
It's not a lot of work, it can be done.

**Comment by WillCodeForCats** [comment]
To do after release v1.2.0

**Comment by WillCodeForCats** [comment]
This feature is complete and will be released as v1.2.1 shortly.
