### ISSUE TITLE
Resetting battery lifetime meters causes log-warning spam

### ISSUE THREAD

**Issue by b3nn0** [WillCodeForCats/solaredge-modbus-multi#264]
**Describe the current behavior**
I have a BYD battery, which is also affected by resetting lifetime import/export meter (I took the liberty to add that to the "Known Issues" wiki page). Therefore I enabled the respective checkbox in the configuration. It's not really an issue, I just configured a utility_meter to add up the changes.
However, this will cause quite a lot of log spamming by this integration:
![grafik](https://user-images.githubusercontent.com/1858945/219873517-7b1f8d1c-98a1-484d-ac5b-36ef6bcb384c.png)

**What should be updated or changed?**
This really shouldn't be a log warning, IMO. but if it is, it probably should only be logged once.
Looking at the code:
https://github.com/WillCodeForCats/solaredge-modbus-multi/blob/f7eadd889545ee578307dc1952e8eae37661217e/custom_components/solaredge_modbus_multi/sensor.py#L1981
and
https://github.com/WillCodeForCats/solaredge-modbus-multi/blob/f7eadd889545ee578307dc1952e8eae37661217e/custom_components/solaredge_modbus_multi/sensor.py#L2049

I can see, there is already the intention to at least only have it logged once per cycle - which is still too much IMO, because the sensor sometimes resets multiple times per hour. However, it doesn't seem to work correctly, not sure why, so the log is spammed for each single reading until the new value is greater than the last peak (I think?)

**Home Assistant (please complete the following information):**
 - Home Assistant Core Version: 2023.2.5
 - solaredge-modbus-multi Version: 2.2.11

**Comment by WillCodeForCats** [comment]
I can just change it to a debug level log.

**Comment by b3nn0** [comment]
Sounds good to me 👍

**Comment by WillCodeForCats** [comment]
This will be in the next pre-release.
