### ISSUE TITLE
Why do you ignore this?

### ISSUE THREAD

**Issue by jiripaskov** [WillCodeForCats/solaredge-modbus-multi#268]
As I wrote. Inverters run well. All data on solaredge website are ok.  So there is no problem with setup. The only problem is that your module sees only 2 out of three. 
This is not a bug for you? This is normal?

Is there something wrong with such questions? Why are you so rude and automatically close any mention about it?

**Comment by WillCodeForCats** [comment]
STOP OPENING ISSUES for setup problems. Open a discussion and maybe someone will help. I don't answer help questions in issues becasue I spent a lot of time working on docs and taking screenshots of exactly what needs to be set so I know your question is answered, but for some reason you refuse to read the docs. Go back and READ the readme and READ the wiki. All of it. Even the parts you don't think mean anything. If you don't understand a specific step in the instructions you can ask that in the HA forums or in a discussion.

You have a setup problem. It's clear you did not read the docs. This is not a "bug".

DO NOT OPEN ISSUES ASKING FOR SETUP HELP. I get alerts for issues and I don't want alerts for people who can't be bothered to follow instructions. If you insist on opening issues over and over for without good reason I will be forced to block you.
