### ISSUE TITLE
is it possible to add 3rd battery?

### ISSUE THREAD

**Issue by danymexi** [WillCodeForCats/solaredge-modbus-multi#276]
Hello,

I have 3 SolarEdge StorEdge batteries. 
But I can not read the 3 batteries connected to my SolarEdge inverter.

Is there a way to read all the 3?

Modbus connection accordingly to SolarEdge support allows up to 16th devices.

Thanks for your help.

**Comment by WillCodeForCats** [comment]
Please do not use issues to ask questions that are already answered in the wiki.
