### ISSUE TITLE
Support for SolarEdge EV Charger connected to Inverter as RS485 Follower

### ISSUE THREAD

**Issue by briadelour** [WillCodeForCats/solaredge-modbus-multi#372]
**Describe the current behavior**
I am using this ModBus integration and pulling more real-time data than the cloud integration.  Works great for my inverter and meter.

**What should be updated or changed?**
Support for SolarEdge EV Charger connected through the RS485 to the Inverter.  Charger is a Follower, Inverter is the Leader.

**Home Assistant (please complete the following information):**
 - Home Assistant Core Version: 2023.7.3
 - solaredge-modbus-multi Version: v2.3.4

**Additional context**
SolarEdge offers an EV charger that can be installed with it's own AC breaker and connect via WiFi or wired ethernet.  However, they also offer an option where the EV charger gets it's AC directly from the inverter from a DIN rail and monitoring is done via an RS485 connection to the inverter.  This avoids the need to use another breaker and adds the capability to draw EV charging from solar or schedule the SolarEdge app to only charge when excess solar is being generated.  The charger is configured as a Follower to the single phase inverter which is set as the Leader much like a multi-inverter set up would be done.  Currently I reload the integration and the EV charger is not found.  The dip switch configuration is identical to setting up other inverters as followers (up to 32).  From the setApp checking the Commissioning status the app reads "S_OK - Server Connected" for the inverter.  All data is feeding to the inverter and displays on the SolarEdge Monitoring App under the Smart Home section.  As a side note, SolarEdge announced a newer version of their EV Charger that will be available in 2024 that will support bidirectional capabilities that would allow the EV to act as a home backup battery through the solar PV system.  Presumably the new charger would connect to the inverter in a similar way.

**Comment by WillCodeForCats** [comment]
https://github.com/WillCodeForCats/solaredge-modbus-multi/discussions/285
