### ISSUE TITLE
Entities not available anymore after automatic firmware update

### ISSUE THREAD

**Issue by john8329** [WillCodeForCats/solaredge-modbus-multi#399]
### Describe the bug

It looks like that after today's update of the inverter to v4.18.32 everything related to the solaredge integration broke. Entities are not available anymore except some basic ones. The battery isn't available too. Everything stopped working since exactly the time of the release, and I suspect it's 90% some integration change. The module is able to connect via Modbus, and isn't reporting errors.

I tried upgrading to 2.4.1 but nothing changed. There's no mention about protocol changes in the [release notes](https://www.solaredge.com/en/support/setapp-inverters-firmware#_Known_Issues_and32) it seems.

### Expected behavior

I expect to see all entities. Right now solar production and battery levels are completely missing.

### Diagnostic File

[config_entry-solaredge_modbus_multi-566b2f71e309bda3d0d7947a9df6bb8a.json.txt](https://github.com/WillCodeForCats/solaredge-modbus-multi/files/12328364/config_entry-solaredge_modbus_multi-566b2f71e309bda3d0d7947a9df6bb8a.json.txt)

### Home Assistant Version

2023.7

### solaredge-modbus-multi Version

2.4.1

### Installation Type

Container

### Read the Instructions

- [X] I have read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki
- [X] My configuration follows https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Configuration

### Additional Context

I should really disconnect the damn inverter from the internet next time.

**Comment by WillCodeForCats** [comment]
Data looks fine to me.

Post a screenshot of your device page.

**Comment by john8329** [comment]
<img width="1025" alt="Screenshot 2023-08-13 at 00 00 31" src="https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/42315498/20d61054-caa6-41af-9194-3680a0f5fa29">

There you go, thanks for the support.

**Comment by WillCodeForCats** [comment]
And of the actual device page once you click on it to show all the sensors and stuff.

**Comment by john8329** [comment]
<img width="1016" alt="Screenshot 2023-08-13 at 00 02 04" src="https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/42315498/92c4787a-012f-4115-a8e6-78fafd42b187">

As you can see some entities are available, but not all of them. I remember being way more.
I believe the official app glitched also today, but it worked after a while.

**Comment by WillCodeForCats** [comment]
I mean that looks normal to me. There aren't more, unless you turn on the ones classified as advanced.

**Comment by WillCodeForCats** [comment]
As far as the battery you will need to run at least [Release v2.4.2-pre.2](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.4.2-pre.2) and newer because SE started omitting an identifier used for battery detection.

**Comment by john8329** [comment]
I'm missing the entity `solar_panel_production_w` which is crucial to know the current solar production. Not sure 100% if it's provided by this module or another calculation, I'll have to check. All I know is that it correlates precisely with the firmware.

I upgraded to the prerelease (was afraid to do it) and now the battery seems to work! Also the production value is now zero and not NaN, I'll have to check tomorrow when photons start raining again.

Guess this is solved with the beta. Thanks again, this integration is amazing and well maintained.

**Comment by WillCodeForCats** [comment]
This is my inverter still running firmware 0004.0014.0229:
<img width="1042" alt="Screenshot 2023-08-12 at 3 08 26 PM" src="https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/48533968/ca2e6862-3d86-4aa7-a35a-7a3d64d34ac6">

So you aren't missing anything in that regard from the update.

**Comment by john8329** [comment]
Good to know (there's one more entity though). Again, not sure where the production value is taken from, but the main problem was the battery. I can dig deeper myself into that in case I encounter more issues.

**Comment by WillCodeForCats** [comment]
There is no entity in this integration called `solar_panel_production_w`.

The default name for inverter power is `sensor.solaredge_iN_ac_power` where `N` is the inverter ID number.

**Comment by john8329** [comment]
You're right, it's calculated as a difference, which is why it glitches sometimes.

**Comment by WillCodeForCats** [comment]
If it's a template sensor there's a couple things to be aware of to make template entities more robust.

First is don't use `round()` in templates. It will error if the entity goes into any non-numeric state (like offline). Instead try using the `rounded=True` property with `states()` like this: `states('sensor.X', rounded=True)` which avoids the use of `round()`, does the same thing, but also applies the entity the default precision setting from the UI.

Second, with templates you can include `availability_template` which defines a template to get the available state of the entity. More information on `availability_template`:

https://www.home-assistant.io/integrations/template/

https://www.home-assistant.io/docs/configuration/templating/#states

https://community.home-assistant.io/t/template-sensor-with-unavailable-sensor/416676

https://community.home-assistant.io/t/how-to-prevent-unavailable-in-template-sensors/398409/3

**Comment by john8329** [comment]
Thanks for the info. I believe a possible cause for the glitch could be a timing difference between sampling from the inverter and the meter. Even half a second can produce a few watts of difference, which then make the panels look like they're producing. 

Not a real concern, and I'm going off topic :)

**Comment by WillCodeForCats** [comment]
Yes that's possible, although they are read as rapidly as possible the inverter data block and the meter data block are indeed separate reads. They can't be read together because it would exceed modbus maximum response size to read at the same time.
