### ISSUE TITLE
still errore on multiple commands

### ISSUE THREAD

**Issue by Condorello** [WillCodeForCats/solaredge-modbus-multi#401]
### Describe the bug

I have an automation that First change the storage default mode to "solar only" (or Charge only etc) and After set the site limit to 1, or 5000 deoending on the automation. The script Works fine, but often Just One setting Is changed,  because the script terminate with this error:

Choose: Option 1 executed
Stopped because an error was encountered at 17 agosto 2023 alle ore 11:03:39 (runtime: 0.01 seconds)
Connection to inverter ID 1 failed.

I already tried to inserti a delay of 1 minute between the command, but nothinf changes.

If i run again the automation by hand also the second setting Is applied.

### Expected behavior

All commands must be processed

### Home Assistant Version

2023.8.2

### solaredge-modbus-multi Version

2.4.2 pre 2

### Installation Type

HAOS

### Read the Instructions

- [X] I have read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki
- [X] My configuration follows https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Configuration

**Comment by WillCodeForCats** [comment]
Try [Release v2.4.2-pre.3](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.4.2-pre.3) and setting Inverter Command Delay between 3-10 seconds.

**Comment by Condorello** [comment]
Seems to be solved with pre.3 and 20ms delay + 30sec pause during the automation... Up and working since 3 days, thanks!
