### ISSUE TITLE
number.solaredge_i1_site_limit unavailable

### ISSUE THREAD

**Issue by raoulteeuwenPE** [WillCodeForCats/solaredge-modbus-multi#407]
### Describe the bug

Hello. Just started using modbus-multi (thank you for making it). In my case, 36 entities are created, but number.solaredge_i1_site_limit reports 'Unavailable'. 

### Expected behavior

number.solaredge_i1_site_limit being available

### Diagnostic File

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.8.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Amsterdam",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.08.1",
    "host_os": "Home Assistant OS 10.5",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "neerslag": {
      "version": "2022.07.07.1",
      "requirements": []
    },
    "solaredgeoptimizers": {
      "version": "1.2.2",
      "requirements": [
        "solaredgeoptimizers==1.0.12",
        "jsonfinder==0.4.2"
      ]
    },
    "wyzeapi": {
      "version": "0.1.22",
      "requirements": [
        "wyzeapy==0.5.20"
      ]
    },
    "ev_smart_charging": {
      "version": "v1.8.0",
      "requirements": []
    },
    "shelly": {
      "version": "1.0.5",
      "requirements": [
        "pyShelly==1.0.3",
        "paho-mqtt==1.6.1",
        "websocket-client"
      ]
    },
    "tesla_custom": {
      "version": "3.15.1",
      "requirements": [
        "teslajsonpy==3.9.2"
      ]
    },
    "battery_sim": {
      "version": "1.0",
      "requirements": []
    },
    "asusrouter": {
      "version": "0.21.1",
      "requirements": [
        "asusrouter==0.20.3"
      ]
    },
    "sonoff": {
      "version": "3.5.2",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "daikin_residential_altherma": {
      "version": "2.8.0",
      "requirements": [
        "oic==1.6.0"
      ]
    },
    "alexa_media": {
      "version": "4.6.5",
      "requirements": [
        "alexapy==1.26.8",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "nodered": {
      "version": "2.2.0",
      "requirements": []
    },
    "nordpool": {
      "version": "0.0.14",
      "requirements": [
        "nordpool>=0.2",
        "backoff"
      ]
    },
    "attributes": {
      "version": "1.2.1",
      "requirements": []
    },
    "entsoe": {
      "version": "0.0.1",
      "requirements": [
        "entsoe-py==0.5.8"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "rpi_rf": {
      "version": "2022.9.0",
      "requirements": [
        "RPi.GPIO==0.7.1",
        "rpi-rf==0.9.7"
      ]
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "solaredge_modbus_multi": {
      "version": "2.4.2",
      "requirements": [
        "pymodbus>=3.3.1"
      ]
    },
    "myenergi": {
      "version": "0.0.23",
      "requirements": [
        "pymyenergi==0.0.27"
      ]
    }
  },
  "integration_manifest": {
    "domain": "solaredge_modbus_multi",
    "name": "SolarEdge Modbus Multi",
    "codeowners": [
      "@WillCodeForCats"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki",
    "integration_type": "hub",
    "iot_class": "local_polling",
    "issue_tracker": "https://github.com/WillCodeForCats/solaredge-modbus-multi/issues",
    "loggers": [
      "custom_components.solaredge_modbus_multi"
    ],
    "requirements": [
      "pymodbus>=3.3.1"
    ],
    "version": "2.4.2",
    "is_built_in": false
  },
  "data": {
    "config_entry": {
      "entry_id": "378fecc30f67e9834fe737614a06156a",
      "version": 1,
      "domain": "solaredge_modbus_multi",
      "title": "SolarEdge",
      "data": {
        "name": "SolarEdge",
        "host": "**REDACTED**",
        "port": 502,
        "number_of_inverters": 1,
        "device_id": 1
      },
      "options": {
        "scan_interval": 300,
        "keep_modbus_open": false,
        "detect_meters": true,
        "detect_batteries": false,
        "advanced_power_control": true,
        "adv_storage_control": false,
        "adv_site_limit_control": true,
        "sleep_after_write": 0
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "inverter_unit_id_1": {
      "device_info": {
        "identifiers": "**REDACTED**",
        "name": "Solaredge I1",
        "manufacturer": "SolarEdge",
        "model": "SE8K",
        "sw_version": "0003.2537",
        "hw_version": ""
      },
      "global_power_control": true,
      "advanced_power_control": true,
      "site_limit_control": true,
      "common": {
        "C_SunSpec_ID": 1400204883,
        "C_SunSpec_DID": 1,
        "C_SunSpec_Length": 65,
        "C_Manufacturer": "SolarEdge",
        "C_Model": "SE8K",
        "C_Option": "",
        "C_Version": "0003.2537",
        "C_SerialNumber": "**REDACTED**",
        "C_Device_address": 1
      },
      "model": {
        "C_SunSpec_DID": "0x67",
        "C_SunSpec_Length": "0x32",
        "AC_Current": "0x4f3",
        "AC_Current_A": "0x1a6",
        "AC_Current_B": "0x1a7",
        "AC_Current_C": "0x1a5",
        "AC_Current_SF": "-0x2",
        "AC_Voltage_AB": "0xfe1",
        "AC_Voltage_BC": "0xfc4",
        "AC_Voltage_CA": "0x1000",
        "AC_Voltage_AN": "0x938",
        "AC_Voltage_BN": "0x8f8",
        "AC_Voltage_CN": "0x925",
        "AC_Voltage_SF": "-0x1",
        "AC_Power": "0x735a",
        "AC_Power_SF": "-0x1",
        "AC_Frequency": "0x1385",
        "AC_Frequency_SF": "-0x2",
        "AC_VA": "0x73da",
        "AC_VA_SF": "-0x1",
        "AC_var": "-0x6bd0",
        "AC_var_SF": "-0x2",
        "AC_PF": "-0x26e3",
        "AC_PF_SF": "-0x2",
        "AC_Energy_WH": "0x20bf014",
        "AC_Energy_WH_SF": "0x0",
        "I_DC_Current": "0xfa2",
        "I_DC_Current_SF": "-0x3",
        "I_DC_Voltage": "0x1d42",
        "I_DC_Voltage_SF": "-0x1",
        "I_DC_Power": "0x751b",
        "I_DC_Power_SF": "-0x1",
        "I_Temp_Cab": "-0x8000",
        "I_Temp_Sink": "0x1446",
        "I_Temp_Trns": "-0x8000",
        "I_Temp_Other": "-0x8000",
        "I_Temp_SF": "-0x2",
        "I_Status": "0x4",
        "I_Status_Vendor": "0x0",
        "I_RRCR": "0x0",
        "I_Power_Limit": "0x64",
        "I_CosPhi": "0x3f800000",
        "I_AdvPwrCtrlEn": "0x1",
        "E_Lim_Ctl_Mode": "0x0",
        "E_Lim_Ctl": "0x1",
        "E_Site_Limit": "0xff7fffff",
        "Ext_Prod_Max": "0x0"
      },
      "is_mmppt": false,
      "mmppt": null,
      "has_battery": null,
      "storage_control": null
    }
  }
}

### Home Assistant Version

2023.8.3

### solaredge-modbus-multi Version

2.4.2

### Installation Type

HAOS

### Read the Instructions

- [X] I have read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki
- [X] My configuration follows https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Configuration

**Comment by WillCodeForCats** [comment]
https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Power-Control-Options#site-limit-control

Try turning it on first.
