### ISSUE TITLE
Storage charge limit to a new value

### ISSUE THREAD

**Issue by zh17home** [WillCodeForCats/solaredge-modbus-multi#441]
**Describe the current behavior**
A clear and concise description of what the feature should be.

Please update the storage charge limit to 8000.

**What should be updated or changed?**
A clear and concise description of the proposed new or updated behavior.

**Home Assistant (please complete the following information):**
 - Home Assistant Core Version: 2023.9.2
 - solaredge-modbus-multi Version: last

**Additional context**
Add any other context about the request here.

After the upgrade to 2023.9.2, I saw the multi set to 6300 to charge the three battery's. I try to change to 8000 but was deny. The last value is 5000. Can you please change to 8000?

Pictures are attached.

**Comment by zh17home** [comment]
Please close the topic is working well after a reload :)

**Comment by WillCodeForCats** [comment]
The battery charge limit value is 50,000 (50kW).

**Comment by zh17home** [comment]
Thanks.
