### ISSUE TITLE
Integration Missing from Devices & Services

### ISSUE THREAD

**Issue by mbillings6** [WillCodeForCats/solaredge-modbus-multi#45]
I installed the repo via HACS and then rebooted HA. after it came back online I went to Devices & Services to add the integration. The only integrations for SolarEdge available where the normal SolarEdge and SolarEdge Modbus. The SolarEdge Modbus Multi wasn't listed. This is the a clean install of SolarEdge Modbus Multi, and it also didn't auto-populate to the integrations page either as some do. I am running Hassio on a RPI4B with version 2022.6.6 and HACS version 1.25.5. Let me know if you need anything to further investigate the issue.

![image](https://user-images.githubusercontent.com/92998610/174927303-63978e8d-7900-41d6-a2eb-5eada560b606.png)

![image](https://user-images.githubusercontent.com/92998610/174927226-3bc27249-286d-469d-b7f7-de58e3353a1b.png)

**Comment by WillCodeForCats** [comment]
What version did you install?

**Comment by WillCodeForCats** [comment]
I tried it on my HACS test VM and I had to reload my browser before it would show up in Home Assistant's integration setup menu.

**Comment by mbillings6** [comment]
I installed v2.0.0, i will give the reload a try. I rebooted hassio several times after the HACS download to no gain.

**Comment by mbillings6** [comment]
I ended up closing my browser out, that did the trick. must be some cache issue with hassio itself.

**Comment by WillCodeForCats** [comment]
I also see when I remove it I have to reload the browser to get it to disappear. My guess is the integration list is cached by the browser and HA isn't dynamically updating it.

**Comment by WillCodeForCats** [comment]
Will add note to reload/restart browser in docs.
