### ISSUE TITLE
No status from inverter

### ISSUE THREAD

**Issue by stickybyte** [WillCodeForCats/solaredge-modbus-multi#453]
### Describe the bug

The integrations gets no status from inverter. It only shows "I_STATUS_MPPT".

### Expected behavior

There should be a number value

### Screenshots

![Bildschirmfoto 2023-10-12 um 11 00 05](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/10342678/3bf628b9-9a19-448a-ba60-5095d6147dea)

### Diagnostic File

none

### Home Assistant Version

2023.10.1

### solaredge-modbus-multi Version

2.4.6

### Installation Type

HAOS

### Read the Instructions

- [X] I have read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki
- [X] My configuration follows https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Configuration
- [X] This issue is not about a template error (template errors should not be reported as an issue, read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Template-Design-Notes)

**Comment by WillCodeForCats** [comment]
There is a numeric value as an attribute.

This is not an issue.
