### ISSUE TITLE
SolarEdge_i1_status

### ISSUE THREAD

**Issue by MarcBotman** [WillCodeForCats/solaredge-modbus-multi#463]
### Describe the bug

On my installation, SolarEdge_i1_status appears as "I_STATUS_SLEEPING" or whatever it is...
It used to be a number 1..8....

### Expected behavior

A number 1..8 or a text

### Screenshots

<img width="412" alt="Screenshot 2023-11-08 at 18 36 02" src="https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/48387606/d2783fa7-a0b5-4c3f-98eb-c4f1158267fe">

### Diagnostic File

xxxxx

### Home Assistant Version

Core 2023.11.1 Supervisor 2023.10.1 Operating System 11.1 Frontend 20231030.1

### solaredge-modbus-multi Version

2.4.6

### Installation Type

HAOS

### Read the Instructions

- [X] I have read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki
- [X] My configuration follows https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Configuration
- [X] This issue is not about a template error (template errors should not be reported as an issue, read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Template-Design-Notes)

**Comment by WillCodeForCats** [comment]
Use the entity attributes if you want the number.

**Comment by WillCodeForCats** [comment]
See attribute `status_value`:

<img width="870" alt="Screenshot 2023-11-08 at 9 51 09 AM" src="https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/48533968/f85bc14f-45b5-42ba-969a-afd01bb6d2a6">

<img width="559" alt="Screenshot 2023-11-08 at 9 50 15 AM" src="https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/48533968/4b473ccd-114a-46b5-9817-eb80d83eb348">

**Comment by MarcBotman** [comment]
Hi,
Did not find that yet! So sorry to have troubled you!
Will be more careful next time.
I just love your integration, cannot live without it!
Kind regards
Marc

**Comment by WillCodeForCats** [comment]
If you want to see attribute values on status cards instead of the default value there is an example in the wiki:

https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Entity-Status-Cards-from-Attributes
