### ISSUE TITLE
Add config option to hold modbus connection open

### ISSUE THREAD

**Issue by WillCodeForCats** [WillCodeForCats/solaredge-modbus-multi#47]
Add config option to hold modbus connection open instead of connecting every polling cycle.

Also consider polling minimum interval less than 10 seconds but require hold open for short polling intervals.

**Comment by mattclar** [comment]
I think this would be a great idea, I'm having connection issues over Wi-Fi, might help a bit to reduce dropouts...
![image](https://user-images.githubusercontent.com/842767/176660318-ce6b1bfb-8420-4860-9678-e29e8074677e.png)

**Comment by WillCodeForCats** [comment]
PR #54 has been created for this option. It will also allow polling intervals under 10 seconds.
