### ISSUE TITLE
wrong voltage in Meter

### ISSUE THREAD

**Issue by on7nh** [WillCodeForCats/solaredge-modbus-multi#479]
### Describe the bug

i see AC voltage AB like -255.61v... when i debus is see valie FAA or 401.0 Volts what scjoud be normal

### Expected behavior

wrong calculation ?

### Screenshots

![Schermafbeelding 2023-11-28 1](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/135119331/cf803a2a-f434-4ed5-a9d4-bf38448dafb2)
![Schermafbeelding 2023-11-28 2](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/135119331/f0756f32-7170-4e02-b81f-9661fabe236d)

### Diagnostic File

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.11.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Brussels",
    "os_name": "Linux",
    "os_version": "6.1.59",
    "supervisor": "2023.11.3",
    "host_os": "Home Assistant OS 11.1",
    "docker_version": "24.0.6",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "victron": {
      "version": "0.0.11",
      "requirements": [
        "pymodbus>=3.5.1"
      ]
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "solaredge_modbus_multi": {
      "version": "2.4.6",
      "requirements": [
        "pymodbus>=3.5.1"
      ]
    },
    "entsoe": {
      "version": "0.0.1",
      "requirements": [
        "entsoe-py==0.5.8"
      ]
    },
    "buienalarm": {
      "version": "1.9",
      "requirements": [
        "pybuienalarm==0.1.1"
      ]
    },
    "nordpool": {
      "version": "0.0.14",
      "requirements": [
        "nordpool>=0.2",
        "backoff"
      ]
    },
    "powertag_gateway": {
      "version": "0.1.1",
      "requirements": [
        "pymodbus==3.5.4"
      ]
    }
  },
  "integration_manifest": {
    "domain": "solaredge_modbus_multi",
    "name": "SolarEdge Modbus Multi",
    "codeowners": [
      "@WillCodeForCats"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki",
    "integration_type": "hub",
    "iot_class": "local_polling",
    "issue_tracker": "https://github.com/WillCodeForCats/solaredge-modbus-multi/issues",
    "loggers": [
      "custom_components.solaredge_modbus_multi"
    ],
    "requirements": [
      "pymodbus>=3.5.1"
    ],
    "version": "2.4.6",
    "is_built_in": false
  },
  "data": {
    "config_entry": {
      "entry_id": "0d05365e88dffb73a7fe7bf042f1f70a",
      "version": 1,
      "domain": "solaredge_modbus_multi",
      "title": "SolarEdge",
      "data": {
        "name": "SolarEdge",
        "host": "**REDACTED**",
        "port": 1502,
        "number_of_inverters": 5,
        "device_id": 1
      },
      "options": {
        "scan_interval": 10,
        "keep_modbus_open": true,
        "detect_meters": true,
        "detect_batteries": true,
        "detect_extras": true,
        "advanced_power_control": true,
        "sleep_after_write": 5,
        "allow_battery_energy_reset": false,
        "battery_energy_reset_cycles": 0,
        "battery_rating_adjust": 0,
        "adv_storage_control": true,
        "adv_site_limit_control": true
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "inverter_unit_id_1": {
      "device_info": {
        "identifiers": "**REDACTED**",
        "name": "Solaredge I1",
        "manufacturer": "SolarEdge",
        "model": "SE10K-RWS48BNN4",
        "sw_version": "0004.0017.0136",
        "hw_version": ""
      },
      "global_power_control": true,
      "advanced_power_control": true,
      "site_limit_control": true,
      "common": {
        "C_SunSpec_ID": 1400204883,
        "C_SunSpec_DID": 1,
        "C_SunSpec_Length": 65,
        "C_Manufacturer": "SolarEdge",
        "C_Model": "SE10K-RWS48BNN4",
        "C_Option": "",
        "C_Version": "0004.0017.0136",
        "C_SerialNumber": "**REDACTED**",
        "C_Device_address": 1
      },
      "model": {
        "C_SunSpec_DID": "0x67",
        "C_SunSpec_Length": "0x32",
        "AC_Current": "0xd01",
        "AC_Current_A": "0x456",
        "AC_Current_B": "0x455",
        "AC_Current_C": "0x456",
        "AC_Current_SF": "-0x2",
        "AC_Voltage_AB": "0xfaa",
        "AC_Voltage_BC": "0xfc7",
        "AC_Voltage_CA": "0xfae",
        "AC_Voltage_AN": "0x8df",
        "AC_Voltage_BN": "0x927",
        "AC_Voltage_CN": "0x92c",
        "AC_Voltage_SF": "-0x1",
        "AC_Power": "0x1e4b",
        "AC_Power_SF": "0x0",
        "AC_Frequency": "0x1386",
        "AC_Frequency_SF": "-0x2",
        "AC_VA": "0x1e51",
        "AC_VA_SF": "0x0",
        "AC_var": "-0xcda",
        "AC_var_SF": "-0x1",
        "AC_PF": "-0x2706",
        "AC_PF_SF": "-0x2",
        "AC_Energy_WH": "0x2666e38",
        "AC_Energy_WH_SF": "0x0",
        "I_DC_Current": "0x2862",
        "I_DC_Current_SF": "-0x3",
        "I_DC_Voltage": "0x1dbf",
        "I_DC_Voltage_SF": "-0x1",
        "I_DC_Power": "0x1ec1",
        "I_DC_Power_SF": "0x0",
        "I_Temp_Cab": "-0x8000",
        "I_Temp_Sink": "0x142b",
        "I_Temp_Trns": "-0x8000",
        "I_Temp_Other": "-0x8000",
        "I_Temp_SF": "-0x2",
        "I_Status": "0x4",
        "I_Status_Vendor": "0x0",
        "I_RRCR": "0x0",
        "I_Power_Limit": "0x64",
        "I_CosPhi": "0x3f800000",
        "I_AdvPwrCtrlEn": "0x1",
        "E_Lim_Ctl_Mode": "0x1",
        "E_Lim_Ctl": "0x0",
        "E_Site_Limit": "0x46abe000",
        "Ext_Prod_Max": "0x0"
      },
      "is_mmppt": false,
      "mmppt": null,
      "has_battery": true,
      "storage_control": {
        "control_mode": "0x4",
        "ac_charge_policy": "0x1",
        "ac_charge_limit": "0x0",
        "backup_reserve": "0x0",
        "default_mode": "0x7",
        "command_timeout": "0xe10",
        "command_mode": "0x7",
        "charge_limit": "0x459c4000",
        "discharge_limit": "0x459c4000"
      }
    },
    "inverter_unit_id_2": {
      "device_info": {
        "identifiers": "**REDACTED**",
        "name": "Solaredge I2",
        "manufacturer": "SolarEdge",
        "model": "SE5K-RWS48BNN4",
        "sw_version": "0004.0017.0131",
        "hw_version": ""
      },
      "global_power_control": true,
      "advanced_power_control": true,
      "site_limit_control": true,
      "common": {
        "C_SunSpec_ID": 1400204883,
        "C_SunSpec_DID": 1,
        "C_SunSpec_Length": 65,
        "C_Manufacturer": "SolarEdge",
        "C_Model": "SE5K-RWS48BNN4",
        "C_Option": "",
        "C_Version": "0004.0017.0131",
        "C_SerialNumber": "**REDACTED**",
        "C_Device_address": 2
      },
      "model": {
        "C_SunSpec_DID": "0x67",
        "C_SunSpec_Length": "0x32",
        "AC_Current": "0x604",
        "AC_Current_A": "0x202",
        "AC_Current_B": "0x201",
        "AC_Current_C": "0x200",
        "AC_Current_SF": "-0x2",
        "AC_Voltage_AB": "0xfb2",
        "AC_Voltage_BC": "0xfd0",
        "AC_Voltage_CA": "0xfb6",
        "AC_Voltage_AN": "0x8e6",
        "AC_Voltage_BN": "0x92d",
        "AC_Voltage_CN": "0x933",
        "AC_Voltage_SF": "-0x1",
        "AC_Power": "0xe04",
        "AC_Power_SF": "0x0",
        "AC_Frequency": "0x1386",
        "AC_Frequency_SF": "-0x2",
        "AC_VA": "0xe0a",
        "AC_VA_SF": "0x0",
        "AC_var": "-0x571c",
        "AC_var_SF": "-0x2",
        "AC_PF": "-0x26fc",
        "AC_PF_SF": "-0x2",
        "AC_Energy_WH": "0xeedd9d",
        "AC_Energy_WH_SF": "0x0",
        "I_DC_Current": "0x12a3",
        "I_DC_Current_SF": "-0x3",
        "I_DC_Voltage": "0x1dd1",
        "I_DC_Voltage_SF": "-0x1",
        "I_DC_Power": "0xe3a",
        "I_DC_Power_SF": "0x0",
        "I_Temp_Cab": "-0x8000",
        "I_Temp_Sink": "0x133c",
        "I_Temp_Trns": "-0x8000",
        "I_Temp_Other": "-0x8000",
        "I_Temp_SF": "-0x2",
        "I_Status": "0x4",
        "I_Status_Vendor": "0x0",
        "I_RRCR": "0x0",
        "I_Power_Limit": "0x64",
        "I_CosPhi": "0x3f800000",
        "I_AdvPwrCtrlEn": "0x1",
        "E_Lim_Ctl_Mode": "0x0",
        "E_Lim_Ctl": "0x0",
        "E_Site_Limit": "0xff7fffff",
        "Ext_Prod_Max": "0x0"
      },
      "is_mmppt": false,
      "mmppt": null,
      "has_battery": true,
      "storage_control": {
        "control_mode": "0x4",
        "ac_charge_policy": "0x1",
        "ac_charge_limit": "0x0",
        "backup_reserve": "0x0",
        "default_mode": "0x0",
        "command_timeout": "0xe10",
        "command_mode": "0x7",
        "charge_limit": "0x459c4000",
        "discharge_limit": "0x459c4000"
      }
    },
    "inverter_unit_id_3": {
      "device_info": {
        "identifiers": "**REDACTED**",
        "name": "Solaredge I3",
        "manufacturer": "SolarEdge",
        "model": "SE7K-RWS48BNN4",
        "sw_version": "0004.0017.0131",
        "hw_version": ""
      },
      "global_power_control": true,
      "advanced_power_control": true,
      "site_limit_control": true,
      "common": {
        "C_SunSpec_ID": 1400204883,
        "C_SunSpec_DID": 1,
        "C_SunSpec_Length": 65,
        "C_Manufacturer": "SolarEdge",
        "C_Model": "SE7K-RWS48BNN4",
        "C_Option": "",
        "C_Version": "0004.0017.0131",
        "C_SerialNumber": "**REDACTED**",
        "C_Device_address": 3
      },
      "model": {
        "C_SunSpec_DID": "0x67",
        "C_SunSpec_Length": "0x32",
        "AC_Current": "0x6ae",
        "AC_Current_A": "0x23b",
        "AC_Current_B": "0x238",
        "AC_Current_C": "0x23b",
        "AC_Current_SF": "-0x2",
        "AC_Voltage_AB": "0xfb3",
        "AC_Voltage_BC": "0xfd5",
        "AC_Voltage_CA": "0xfbb",
        "AC_Voltage_AN": "0x8e7",
        "AC_Voltage_BN": "0x92d",
        "AC_Voltage_CN": "0x931",
        "AC_Voltage_SF": "-0x1",
        "AC_Power": "0xf91",
        "AC_Power_SF": "0x0",
        "AC_Frequency": "0x1385",
        "AC_Frequency_SF": "-0x2",
        "AC_VA": "0xf99",
        "AC_VA_SF": "0x0",
        "AC_var": "-0x67e8",
        "AC_var_SF": "-0x2",
        "AC_PF": "-0x26f9",
        "AC_PF_SF": "-0x2",
        "AC_Energy_WH": "0x2074148",
        "AC_Energy_WH_SF": "0x0",
        "I_DC_Current": "0x14bb",
        "I_DC_Current_SF": "-0x3",
        "I_DC_Voltage": "0x1dc5",
        "I_DC_Voltage_SF": "-0x1",
        "I_DC_Power": "0xfcd",
        "I_DC_Power_SF": "0x0",
        "I_Temp_Cab": "-0x8000",
        "I_Temp_Sink": "0xd8e",
        "I_Temp_Trns": "-0x8000",
        "I_Temp_Other": "-0x8000",
        "I_Temp_SF": "-0x2",
        "I_Status": "0x4",
        "I_Status_Vendor": "0x0",
        "I_RRCR": "0x0",
        "I_Power_Limit": "0x64",
        "I_CosPhi": "0x3f800000",
        "I_AdvPwrCtrlEn": "0x1",
        "E_Lim_Ctl_Mode": "0x0",
        "E_Lim_Ctl": "0x0",
        "E_Site_Limit": "0xff7fffff",
        "Ext_Prod_Max": "0x0"
      },
      "is_mmppt": false,
      "mmppt": null,
      "has_battery": true,
      "storage_control": {
        "control_mode": "0x4",
        "ac_charge_policy": "0x1",
        "ac_charge_limit": "0x0",
        "backup_reserve": "0x0",
        "default_mode": "0x0",
        "command_timeout": "0xe10",
        "command_mode": "0x7",
        "charge_limit": "0x459c4000",
        "discharge_limit": "0x459c4000"
      }
    },
    "inverter_unit_id_4": {
      "device_info": {
        "identifiers": "**REDACTED**",
        "name": "Solaredge I4",
        "manufacturer": "SolarEdge",
        "model": "SE4K-RW0TEBNN4",
        "sw_version": "0004.0018.0032",
        "hw_version": ""
      },
      "global_power_control": true,
      "advanced_power_control": true,
      "site_limit_control": true,
      "common": {
        "C_SunSpec_ID": 1400204883,
        "C_SunSpec_DID": 1,
        "C_SunSpec_Length": 65,
        "C_Manufacturer": "SolarEdge",
        "C_Model": "SE4K-RW0TEBNN4",
        "C_Option": "",
        "C_Version": "0004.0018.0032",
        "C_SerialNumber": "**REDACTED**",
        "C_Device_address": 4
      },
      "model": {
        "C_SunSpec_DID": "0x67",
        "C_SunSpec_Length": "0x32",
        "AC_Current": "0x234",
        "AC_Current_A": "0xbc",
        "AC_Current_B": "0xbd",
        "AC_Current_C": "0xba",
        "AC_Current_SF": "-0x2",
        "AC_Voltage_AB": "0xfb5",
        "AC_Voltage_BC": "0xfd9",
        "AC_Voltage_CA": "0xfc1",
        "AC_Voltage_AN": "0x8e8",
        "AC_Voltage_BN": "0x930",
        "AC_Voltage_CN": "0x938",
        "AC_Voltage_SF": "-0x1",
        "AC_Power": "0x32a0",
        "AC_Power_SF": "-0x1",
        "AC_Frequency": "0x1386",
        "AC_Frequency_SF": "-0x2",
        "AC_VA": "0x3383",
        "AC_VA_SF": "-0x1",
        "AC_var": "-0x5f50",
        "AC_var_SF": "-0x2",
        "AC_PF": "-0x2661",
        "AC_PF_SF": "-0x2",
        "AC_Energy_WH": "0x53c6ee",
        "AC_Energy_WH_SF": "0x0",
        "I_DC_Current": "0x44c6",
        "I_DC_Current_SF": "-0x4",
        "I_DC_Voltage": "0x1d31",
        "I_DC_Voltage_SF": "-0x1",
        "I_DC_Power": "0x3365",
        "I_DC_Power_SF": "-0x1",
        "I_Temp_Cab": "-0x8000",
        "I_Temp_Sink": "0xa05",
        "I_Temp_Trns": "-0x8000",
        "I_Temp_Other": "-0x8000",
        "I_Temp_SF": "-0x2",
        "I_Status": "0x4",
        "I_Status_Vendor": "0x0",
        "I_RRCR": "0x0",
        "I_Power_Limit": "0x64",
        "I_CosPhi": "0x3f800000",
        "I_AdvPwrCtrlEn": "0x1",
        "E_Lim_Ctl_Mode": "0x0",
        "E_Lim_Ctl": "0x0",
        "E_Site_Limit": "0xff7fffff",
        "Ext_Prod_Max": "0x0"
      },
      "is_mmppt": false,
      "mmppt": null,
      "has_battery": false,
      "storage_control": {
        "control_mode": "0x0",
        "ac_charge_policy": "0x1",
        "ac_charge_limit": "0x0",
        "backup_reserve": "0x0",
        "default_mode": "0x0",
        "command_timeout": "0xe10",
        "command_mode": "0x7",
        "charge_limit": "0x45a8c000",
        "discharge_limit": "0x45a8c000"
      }
    },
    "inverter_unit_id_5": {
      "device_info": {
        "identifiers": "**REDACTED**",
        "name": "Solaredge I5",
        "manufacturer": "SolarEdge",
        "model": "SE4K-RW0TEBNN4",
        "sw_version": "0004.0018.0032",
        "hw_version": ""
      },
      "global_power_control": true,
      "advanced_power_control": true,
      "site_limit_control": true,
      "common": {
        "C_SunSpec_ID": 1400204883,
        "C_SunSpec_DID": 1,
        "C_SunSpec_Length": 65,
        "C_Manufacturer": "SolarEdge",
        "C_Model": "SE4K-RW0TEBNN4",
        "C_Option": "",
        "C_Version": "0004.0018.0032",
        "C_SerialNumber": "**REDACTED**",
        "C_Device_address": 5
      },
      "model": {
        "C_SunSpec_DID": "0x67",
        "C_SunSpec_Length": "0x32",
        "AC_Current": "0x2d7",
        "AC_Current_A": "0xf1",
        "AC_Current_B": "0xf5",
        "AC_Current_C": "0xf0",
        "AC_Current_SF": "-0x2",
        "AC_Voltage_AB": "0xfc5",
        "AC_Voltage_BC": "0xfe2",
        "AC_Voltage_CA": "0xfc8",
        "AC_Voltage_AN": "0x8f1",
        "AC_Voltage_BN": "0x936",
        "AC_Voltage_CN": "0x93a",
        "AC_Voltage_SF": "-0x1",
        "AC_Power": "0x41fa",
        "AC_Power_SF": "-0x1",
        "AC_Frequency": "0x1385",
        "AC_Frequency_SF": "-0x2",
        "AC_VA": "0x4284",
        "AC_VA_SF": "-0x1",
        "AC_var": "-0x54c4",
        "AC_var_SF": "-0x2",
        "AC_PF": "-0x26bd",
        "AC_PF_SF": "-0x2",
        "AC_Energy_WH": "0x8df3e2",
        "AC_Energy_WH_SF": "0x0",
        "I_DC_Current": "0x5985",
        "I_DC_Current_SF": "-0x4",
        "I_DC_Voltage": "0x1d3a",
        "I_DC_Voltage_SF": "-0x1",
        "I_DC_Power": "0x42fb",
        "I_DC_Power_SF": "-0x1",
        "I_Temp_Cab": "-0x8000",
        "I_Temp_Sink": "0xa38",
        "I_Temp_Trns": "-0x8000",
        "I_Temp_Other": "-0x8000",
        "I_Temp_SF": "-0x2",
        "I_Status": "0x4",
        "I_Status_Vendor": "0x0",
        "I_RRCR": "0x0",
        "I_Power_Limit": "0x64",
        "I_CosPhi": "0x3f800000",
        "I_AdvPwrCtrlEn": "0x1",
        "E_Lim_Ctl_Mode": "0x0",
        "E_Lim_Ctl": "0x0",
        "E_Site_Limit": "0xff7fffff",
        "Ext_Prod_Max": "0x0"
      },
      "is_mmppt": false,
      "mmppt": null,
      "has_battery": false,
      "storage_control": {
        "control_mode": "0x0",
        "ac_charge_policy": "0x1",
        "ac_charge_limit": "0x0",
        "backup_reserve": "0x0",
        "default_mode": "0x0",
        "command_timeout": "0xe10",
        "command_mode": "0x7",
        "charge_limit": "0x45a8c000",
        "discharge_limit": "0x45a8c000"
      }
    },
    "meter_id_1": {
      "device_info": {
        "identifiers": "**REDACTED**",
        "name": "Solaredge M1",
        "manufacturer": "WattNode",
        "model": "WND-3Y-400-MB",
        "sw_version": "31",
        "hw_version": "Export+Import",
        "via_device": [
          "solaredge_modbus_multi",
          "SE10K-RWS48BNN4_7E044DE8"
        ]
      },
      "inverter_unit_id": 1,
      "common": {
        "C_SunSpec_DID": 1,
        "C_SunSpec_Length": 65,
        "C_Manufacturer": "WattNode",
        "C_Model": "WND-3Y-400-MB",
        "C_Option": "Export+Import",
        "C_Version": "31",
        "C_SerialNumber": "**REDACTED**",
        "C_Device_address": 2
      },
      "model": {
        "C_SunSpec_DID": "0xcb",
        "C_SunSpec_Length": "0x69",
        "AC_Current": "-0x20e",
        "AC_Current_A": "-0x4e",
        "AC_Current_B": "-0xed",
        "AC_Current_C": "-0xd2",
        "AC_Current_SF": "-0x1",
        "AC_Voltage_LN": "0x58da",
        "AC_Voltage_AN": "0x58da",
        "AC_Voltage_BN": "0x5bbb",
        "AC_Voltage_CN": "0x5bde",
        "AC_Voltage_LL": "-0x62b7",
        "AC_Voltage_AB": "-0x6376",
        "AC_Voltage_BC": "-0x61f1",
        "AC_Voltage_CA": "-0x62bf",
        "AC_Voltage_SF": "-0x2",
        "AC_Frequency": "0x1385",
        "AC_Frequency_SF": "-0x2",
        "AC_Power": "0x2e8d",
        "AC_Power_A": "0x5aa",
        "AC_Power_B": "0x15ce",
        "AC_Power_C": "0x1314",
        "AC_Power_SF": "0x0",
        "AC_VA": "0x2ef8",
        "AC_VA_A": "0x672",
        "AC_VA_B": "0x15d8",
        "AC_VA_C": "0x132b",
        "AC_VA_SF": "0x0",
        "AC_var": "-0x63e",
        "AC_var_A": "-0x313",
        "AC_var_B": "-0x151",
        "AC_var_C": "-0x1d8",
        "AC_var_SF": "0x0",
        "AC_PF": "-0x2489",
        "AC_PF_A": "-0x2060",
        "AC_PF_B": "-0x26c8",
        "AC_PF_C": "-0x2674",
        "AC_PF_SF": "-0x2",
        "AC_Energy_WH_Exported": "0x2226888",
        "AC_Energy_WH_Exported_A": "0xb4a477",
        "AC_Energy_WH_Exported_B": "0x1138f5a",
        "AC_Energy_WH_Exported_C": "0xe7730e",
        "AC_Energy_WH_Imported": "0x19e5580",
        "AC_Energy_WH_Imported_A": "0x11724ea",
        "AC_Energy_WH_Imported_B": "0x6c6319",
        "AC_Energy_WH_Imported_C": "0xa80bd4",
        "AC_Energy_WH_SF": "0x0",
        "M_VAh_Exported": "0x0",
        "M_VAh_Exported_A": "0x0",
        "M_VAh_Exported_B": "0x0",
        "M_VAh_Exported_C": "0x0",
        "M_VAh_Imported": "0x0",
        "M_VAh_Imported_A": "0x0",
        "M_VAh_Imported_B": "0x0",
        "M_VAh_Imported_C": "0x0",
        "M_VAh_SF": "-0x8000",
        "M_varh_Import_Q1": "0x0",
        "M_varh_Import_Q1_A": "0x0",
        "M_varh_Import_Q1_B": "0x0",
        "M_varh_Import_Q1_C": "0x0",
        "M_varh_Import_Q2": "0x0",
        "M_varh_Import_Q2_A": "0x0",
        "M_varh_Import_Q2_B": "0x0",
        "M_varh_Import_Q2_C": "0x0",
        "M_varh_Export_Q3": "0x0",
        "M_varh_Export_Q3_A": "0x0",
        "M_varh_Export_Q3_B": "0x0",
        "M_varh_Export_Q3_C": "0x0",
        "M_varh_Export_Q4": "0x0",
        "M_varh_Export_Q4_A": "0x0",
        "M_varh_Export_Q4_B": "0x0",
        "M_varh_Export_Q4_C": "0x0",
        "M_varh_SF": "-0x8000",
        "M_Events": "0x0"
      }
    },
    "battery_id_1": {
      "device_info": {
        "identifiers": "**REDACTED**",
        "name": "Solaredge B1",
        "manufacturer": "48V_BYD",
        "model": "BYD Premium LVS 24.0",
        "sw_version": "48V DCDC 2.2.132 BMS 0.0.0",
        "via_device": [
          "solaredge_modbus_multi",
          "SE7K-RWS48BNN4_7E0425A8"
        ]
      },
      "inverter_unit_id": 3,
      "common": {
        "B_Manufacturer": "48V_BYD",
        "B_Model": "BYD Premium LVS 24.0",
        "B_Version": "48V DCDC 2.2.132 BMS 0.0.0",
        "B_SerialNumber": "**REDACTED**",
        "B_Device_Address": 112,
        "B_RatedEnergy": 24000.0,
        "B_MaxChargePower": 13200.0,
        "B_MaxDischargePower": 13200.0,
        "B_MaxChargePeakPower": 22750.0,
        "B_MaxDischargePeakPower": 22750.0
      },
      "model": {
        "B_Temp_Average": "0x41880000",
        "B_Temp_Max": "0x0",
        "B_DC_Voltage": "0x443f4a45",
        "B_DC_Current": "0x3d15e8ad",
        "B_DC_Power": "0x0",
        "B_Export_Energy_WH": "0x0",
        "B_Import_Energy_WH": "0xea",
        "B_Energy_Max": "0x46bb8000",
        "B_Energy_Available": "0x46b7c000",
        "B_SOH": "0x42c40000",
        "B_SOE": "0x42c80000",
        "B_Status": "0x6",
        "B_Status_Vendor": "0x3",
        "B_Event_Log1": "0x0",
        "B_Event_Log2": "0x0",
        "B_Event_Log3": "0x0",
        "B_Event_Log4": "0x0",
        "B_Event_Log5": "0x0",
        "B_Event_Log6": "0x0",
        "B_Event_Log7": "0x0",
        "B_Event_Log8": "0x0",
        "B_Event_Log_Vendor1": "0x0",
        "B_Event_Log_Vendor2": "0x0",
        "B_Event_Log_Vendor3": "0x0",
        "B_Event_Log_Vendor4": "0x0",
        "B_Event_Log_Vendor5": "0x0",
        "B_Event_Log_Vendor6": "0x0",
        "B_Event_Log_Vendor7": "0x0",
        "B_Event_Log_Vendor8": "0x0"
      }
    }
  }
}

### Home Assistant Version

2023.11.1

### solaredge-modbus-multi Version

2.4.6

### Installation Type

HAOS

### Read the Instructions

- [X] I have read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki
- [X] My configuration follows https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Configuration
- [X] This issue is not about a template error (template errors should not be reported as an issue, read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Template-Design-Notes)

### Additional Context

.

**Comment by WillCodeForCats** [comment]
The screenshots aren't from the same devices, that's why they don't match.

**Comment by on7nh** [comment]
the screenshots are a minute later.

if you look at

"AC_Voltage_AN": "0x8df", is this 2271 or 227.1 volts..this corresponds approximately to 226.36

but if you take "AC_Voltage_AB": "0xfaa", it should be 401 volts...
include some variation in time... but this can never be -255.64 volts...
this number is Negative...

**Comment by WillCodeForCats** [comment]
Closing because I can't see or duplicate the issue in the integration.
