### ISSUE TITLE
Platform solaredge_modbus_multi does not generate unique IDs.

### ISSUE THREAD

**Issue by purcell-lab** [WillCodeForCats/solaredge-modbus-multi#50]
Everything appears to be working correctly. I have two inverters and one meter which are all correct.

**Describe the bug**
I get an error message in the logs about unique IDs, which I suspect is related to 2022.7 beta release.

**Expected behavior**
Integration should generate unique IDs and not report an error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/79175134/176982637-784098f8-b47d-436a-bdc3-33a6ce0a4fce.png)
![image](https://user-images.githubusercontent.com/79175134/176982655-bf3b6033-bbee-4fe3-b841-4c64b9b8e823.png)
![image](https://user-images.githubusercontent.com/79175134/176982667-e0844a84-365c-41b6-9fba-3f3ac1a66ae7.png)
![image](https://user-images.githubusercontent.com/79175134/176982675-c7f4c725-4100-44cc-bbee-9267430971c0.png)

**Logs**
Copy any log messages/errors from Home Assistant from "custom_components.solaredge_modbus" and "pymodbus.client.sync".

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:620
Integration: Sensor (documentation, issues)
First occurred: 11:54:24 AM (28 occurrences)
Last logged: 11:54:24 AM

Platform solaredge_modbus_multi does not generate unique IDs. ID SE-MTR-3Y-400V-A_606773955_exported_c_kwh already exists - ignoring sensor.solaredge_m1_exported_c_kwh
Platform solaredge_modbus_multi does not generate unique IDs. ID SE-MTR-3Y-400V-A_606773955_imported_kwh already exists - ignoring sensor.solaredge_m1_imported_kwh
Platform solaredge_modbus_multi does not generate unique IDs. ID SE-MTR-3Y-400V-A_606773955_imported_a_kwh already exists - ignoring sensor.solaredge_m1_imported_a_kwh
Platform solaredge_modbus_multi does not generate unique IDs. ID SE-MTR-3Y-400V-A_606773955_imported_b_kwh already exists - ignoring sensor.solaredge_m1_imported_b_kwh
Platform solaredge_modbus_multi does not generate unique IDs. ID SE-MTR-3Y-400V-A_606773955_imported_c_kwh already exists - ignoring sensor.solaredge_m1_imported_c_kwh

**Home Assistant (please complete the following information):**
- Home Assistant 2022.7.0b2
- Supervisor 2022.06.2
- Frontend 20220630.0 - latest
 - solaredge-modbus-multi Version: 2.0.0

**Additional context**
I deleted the old integrations before installing 2.0.0, all the history came across correctly.

**Comment by WillCodeForCats** [comment]
I tried installing core-2022.7.0b2 on my dev virtual machine, but was not able to duplicate the issue.

**Comment by WillCodeForCats** [comment]
Did you manually rename the device to "Solaredge M2" or did it create it like that? It should be M1.

**Comment by WillCodeForCats** [comment]
Can you also provide all of the attributes from entity `sensor.solaredge_m1_device`

**Comment by WillCodeForCats** [comment]
I added a check to ignore duplicate meter serial numbers, in case the same meter is being reported multiple times. The unique ID relies on the device model and serial number, where the serial number must be unique to each device model.

Please try this branch: https://github.com/WillCodeForCats/solaredge-modbus-multi/archive/refs/heads/50-platform-solaredge_modbus_multi-does-not-generate-unique-ids.zip

**Comment by purcell-lab** [comment]
> Did you manually rename the device to "Solaredge M2" or did it create it like that? It should be M1.

No I didn't rename anything, this is how it auto configured.

**Comment by purcell-lab** [comment]
> Can you also provide all of the attributes from entity `sensor.solaredge_m1_device`

Here are the attributes.

![Screenshot_20220702-144836](https://user-images.githubusercontent.com/79175134/176986928-a4ed2a94-e05b-4f0f-9dc2-eb011f8bc563.png)

**Comment by WillCodeForCats** [comment]
The only thing I can think of is that somehow the same meter is being reported more than once, which the branch should fix by ignoring meters where a device was already created with the same serial number.

**Comment by purcell-lab** [comment]
2.0.1 Has opened up an new error message for me. 

Functionality does't appear impacted.

```
This error originated from a custom integration.

Logger: custom_components.solaredge_modbus_multi.hub
Source: custom_components/solaredge_modbus_multi/hub.py:105
Integration: SolarEdge Modbus Multi-Inverter (documentation, issues)
First occurred: 9:06:50 AM (1 occurrences)
Last logged: 9:06:50 AM

Duplicate serial 606773955. Ignoring meter 2 on inverter ID 1
```
![image](https://user-images.githubusercontent.com/79175134/177018638-5cf1f527-ec1e-42bb-8c92-fd3073dc050a.png)

**Comment by WillCodeForCats** [comment]
That is just saying there was a duplicate found and it was ignored. Everything looks correct to me.

The issue of why the same meter is being reported more than once would be an issue to look into on the hardware side (is the meter somehow connected to both inverters?) but otherwise not an error with the integration.

**Comment by WillCodeForCats** [comment]
The duplicate detected message will now display at `warning` level instead of `error` level in release v2.0.2.
