### ISSUE TITLE
Plugin should accept hostnames like 'bc3b947b-modbus-proxy' as inverter IP address

### ISSUE THREAD

**Issue by schuettecarsten** [WillCodeForCats/solaredge-modbus-multi#554]
I use modbus-proxy addon for Home Assistant. This works fine but I have to use 127.0.0.1 as inverter address and expose the modbus proxy port. It would be great if your extension would accept the local addon hostname as inverter IP address.

![image](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/1275166/eb1fd2a7-872d-4910-997f-83b39ea8b002)

![image](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/1275166/86bfde60-9217-486c-b4f4-65714038b111)

**Comment by WillCodeForCats** [comment]
I must have missed something from my other integration (tekmar-482 accepts host names like this).

**Comment by WillCodeForCats** [comment]
Fixed in [Release v2.4.12-pre.4](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.4.12-pre.4)

**Comment by schuettecarsten** [comment]
Works, thank you!
