### ISSUE TITLE
SE Inverter Software version not updated

### ISSUE THREAD

**Issue by mtbsteve** [WillCodeForCats/solaredge-modbus-multi#571]
### Describe the bug

Minor issue - I noticed that the SE inverter version does not get updated in HA when the inverter has been updated to a new version. Currently, you need to reload the adapter in order to read the current version string. 

### Expected behavior

The inverter version should get updated once the version changes on the inverter.

### Screenshots

![bild2](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/11302624/ddabf42b-3d5d-4d61-8fb3-f49e220e58ec)

### Diagnostic File

none

### Home Assistant Version

2024.3.3

### solaredge-modbus-multi Version

2.4.13

### Installation Type

HAOS

### Read the Instructions

- [X] I have read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki
- [X] My configuration follows https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Configuration
- [X] This issue is not about a template error (template errors should not be reported as an issue, read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Template-Design-Notes)

**Comment by WillCodeForCats** [comment]
This is how HA works, not an issue with the integration.

Refer to the version sensor instead for live updates.

**Comment by WillCodeForCats** [comment]
Actually you're right, I was thinking about something else.

**Comment by WillCodeForCats** [comment]
I'm not sure that the value in the device info card can be updated dynamically. I'm not seeing an update method in the HA docs (https://developers.home-assistant.io/docs/device_registry_index/). According to the docs, device info is read once at startup.

The version sensor entity can update dynamically, of course.
