### ISSUE TITLE
Battery export sensor incorrect

### ISSUE THREAD

**Issue by jongbj1972** [WillCodeForCats/solaredge-modbus-multi#580]
### Describe the bug

The battery export sensor indicates a battery discharge of only 3kWh/day while reality is approx. 12kWh/day

### Expected behavior

correct data being read from the battery export sensor

### Screenshots

![image](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/109912509/25dd3bba-2f3f-4bff-8c60-e3ac552512e9)
![image](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/109912509/f461eb58-d148-4acb-93fa-920a5e45ea7c)
![image](https://github.com/WillCodeForCats/solaredge-modbus-multi/assets/109912509/17f70e14-72f5-4bd5-9e81-7217775654bd)

### Diagnostic File

As it is a continued problem, there is not a specific moment.

### Debug logs

```shell
As it is a continued problem, there is not a specific moment.
```

### Home Assistant Version

2024.4.1

### solaredge-modbus-multi Version

latetst

### Installation Type

HAOS

### Read the Instructions

- [X] I have read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki
- [X] My configuration follows https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Configuration
- [X] This issue is not about a template error (template errors should not be reported as an issue, read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Template-Design-Notes)

### Additional Context

Up until recently, the battery export sensor functioned fine, although, due to a database change, I cannot dettermine when it started to go wrong, but it is clearly visible that the data is not correct.

**Comment by WillCodeForCats** [comment]
Closing because there is no diagnostic file.

Please resubmit with the information I need.
