### ISSUE TITLE
Storage Command Mode reset after 1 second

### ISSUE THREAD

**Issue by treynaer** [WillCodeForCats/solaredge-modbus-multi#589]
### Describe the bug

Storage Control Mode is set to remote control.
Storage Command Mode is set to Discharge to maximize export.
Storage Discharge Limit is set to 400W.
The inverter starts discharging of the battery for 1-2 seconds and reverts back to Maximize Self Consumption.

### Expected behavior

The inverted needs to export for the duration of Storage Command Timeout.

### Diagnostic File

[config_entry-solaredge_modbus_multi.json](https://github.com/WillCodeForCats/solaredge-modbus-multi/files/15062676/config_entry-solaredge_modbus_multi.json)

### Home Assistant Version

2024.4.3

### solaredge-modbus-multi Version

2.4.13

### Installation Type

Container

### Read the Instructions

- [X] I have read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki
- [X] My configuration follows https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Configuration
- [X] This issue is not about a template error (template errors should not be reported as an issue, read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Template-Design-Notes)

**Comment by WillCodeForCats** [comment]
This is not the integration.

Check the battery discussions for assistance or ask SolarEdge to un-enroll from whatever program causes this. I don't have batters so I can't really help with battery questions.
