### ISSUE TITLE
Support for two inverters with different IP-adress

### ISSUE THREAD

**Issue by corneel27** [WillCodeForCats/solaredge-modbus-multi#62]
I tried to find my question/solution in your documentation, the issues and the comments, but I found nothing.
How can I use your component  for two (or more) inverters in my local network, which are not connected by rs485?
Thank you in advance.

**Comment by WillCodeForCats** [comment]
Add the integration multiple times.

**Comment by corneel27** [comment]
Thank you for your fast response.
It works!!
