### ISSUE TITLE
new BinarySensor "Grid Status" should be BinarySensorDeviceClass = Energy

### ISSUE THREAD

**Issue by ChristophCaina** [WillCodeForCats/solaredge-modbus-multi#624]
**Describe the current behavior**
The current BinarySensor "Grid Status" does not have a default BinarySensorDeviceClass.
You can select the deviceClass in the Entity Settings, but I think, it should be "Energy" by default.
By having a specific DeviceClass assigned, the BinarySensor can be selected as alert-class in the Area-Card, like shown in this screenshot.

![image](https://github.com/user-attachments/assets/db330923-68f7-4f55-9907-63f40a19a4d8)

This Icon will be shown, whenever the Sensor is "ON"

Since an alarm should be displayed whenever there's a "problem", I think the logic should be inverted - but this would be something that needs to be done from HomeAssistant.

**What should be updated or changed?**
The Binary Sensor "Grid Status" should have a default BinarySensorDeviceClass, preferred "Energy"

**Home Assistant (please complete the following information):**
 - Home Assistant Core Version: 2024.7.2
 - solaredge-modbus-multi Version: 2.4.17

**Additional context**
Add any other context about the request here.

**Comment by WillCodeForCats** [comment]
ENERGY is not a supported class for binary sensor.

https://developers.home-assistant.io/docs/core/entity/binary-sensor

POWER is an option though.

**Comment by ChristophCaina** [comment]
Sorry, this was a translation mistake, since the deviceClass was translated as "Energy" into german ... :D

**Comment by WillCodeForCats** [comment]
Testing the PR and I will merge it as soon as I check it on my test system.

**Comment by ChristophCaina** [comment]
thanks :)

I have implemented the changes, and everything seems to work.
Yet, as I have already set the deviceclass, I can't really check the difference ^^

But at least, nothing unexpected observed so far.

**Comment by WillCodeForCats** [comment]
[Release v2.4.18](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.4.18)
