### ISSUE TITLE
Unable to connect to SolarEdge Inverter and Battery

### ISSUE THREAD

**Issue by peterlazeris** [WillCodeForCats/solaredge-modbus-multi#715]
### Describe the bug

I have followed the installation and configuration guidelines and have enabled Modbus in the inverter which set to be using port 1502 as per your example. I have now added the HACS repository and added the SolarEdge Integration. In the integration, I entered the fixed network address of 192.168.2.252 with Port of 1502. When I click Submit the integration is added but there is a warning <Failed Setup, will retry>. 

I can see the integration is continuing to attempt a connection every few seconds but it is not connecting. I restarted HA after completing the HACS download and again after configuring the integration. 

I have just read another recent post about the possibility the latest version of HA may have affected how this integration connects. I was running HA Core 2024.12.4 but while doing the configuration today an update to 2024.12.5 appeared so I updated to that hoping it may resolve this but unfortunately it didn't. I have also tried changing the default settings for the SolarEdge Integration but this didn't help either. I also tried uninstalling the HACS integration and downloaded an older version but that didn't work so I am currently back with 3.0.3 but not connecting.

I have enabled debug logging but currently I cannot see where to access the debug file to send to you.

### Expected behavior

I was hoping that once the configuration was completed I would start to receive live data directly from my inverter and the available sensors.

### Screenshots

![image](https://github.com/user-attachments/assets/3690671b-9444-4c36-a41a-149e90fe2402)
![image](https://github.com/user-attachments/assets/caae1c1a-3798-4053-805f-593352a99955)
![image](https://github.com/user-attachments/assets/7a87e79d-5a37-4b92-add9-69044b0cf2ef)
![image](https://github.com/user-attachments/assets/34df17e8-0162-4d3d-8c71-1d0127cbc443)
![image](https://github.com/user-attachments/assets/d41bb6b7-4fd4-4b07-8d1d-54318e60a535)

### Diagnostic File

I have enabled debugging but I cannot see where to download the debugging file 
![image](https://github.com/user-attachments/assets/13ce0f14-b4f8-4239-a9e2-46048d8592f8)

### Home Assistant Version

2024.12.4

### solaredge-modbus-multi Version

3.0.3

### Installation Type

HAOS

### Read the Instructions

- [X] My configuration follows https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Configuration
- [X] I have read the Known Issues https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Known-Issues
- [X] This issue is not about a template error (do not report template errors, read https://github.com/WillCodeForCats/solaredge-modbus-multi/wiki/Template-Design-Notes)

**Comment by WillCodeForCats** [comment]
You can only have one connection to a SolarEdge inverter at a time. Other integrations will block the connection. You will need to uninstall the other solarege modbus integration (or disable/remove its devices) to use this one.
