### ISSUE TITLE
Energy Meter with Modbus Connection not recognized

### ISSUE THREAD

**Issue by hoeselr** [WillCodeForCats/solaredge-modbus-multi#85]
Setup

SE82.8K Inverter on Modbus address 2
Solaredge Energy Meter connected to Inverter on Modbus address 1 but not recognized by [solaredge-modbus-multi] as sensor.

![Screenshot 2022-08-24 132405](https://user-images.githubusercontent.com/33808979/186406606-6cc9e0cc-fcee-4c47-8694-84fee4a8980b.jpg)

**Comment by WillCodeForCats** [comment]
Attach the list of attributes for entities `sensor.solaredge_i1_device` and `sensor.solaredge_i2_device` and the list of devices for the integration.

**Comment by WillCodeForCats** [comment]
Thanks, I will work on this.

**Comment by hoeselr** [comment]
@WillCodeForCats 
thank you very much!

**Comment by WillCodeForCats** [comment]
Please try Pre-[Release v2.2.0-mmppt.1](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.2.0-mmppt.1)

**Comment by hoeselr** [comment]
@WillCodeForCats 

now it works like a charm - SE-MTR-3Y-400V-A successfully discovered on Modbus address 1  - thank you!

![2022-08-27_11-41-34](https://user-images.githubusercontent.com/33808979/187024733-d96912cf-3d36-4ec6-adbf-4c0126d23485.jpg)

**Comment by WillCodeForCats** [comment]
[Pre-Release v2.2.0-pre.2](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.2.0-pre.2)

This pre-release also adds a new mmppt events sensor.

**Comment by hoeselr** [comment]
@WillCodeForCats 

after the update the integration is not able to communicate with inverter, we also tried fresh install : following Message in logfile

Logger: pymodbus.client.sync
Source: /usr/local/lib/python3.10/site-packages/pymodbus/client/sync.py:218 
First occurred: 18:26:00 (1 occurrences) 
Last logged: 18:26:00

Connection to (10.31.1.240, 1502) failed: [Errno 111] Connection refused

**Comment by WillCodeForCats** [comment]
Unless there are any exception errors, "connection refused" is a response from the inverter.

**Comment by WillCodeForCats** [comment]
SolarEdge inverters can only handle one connection at a time, so if it thinks something else is connected it will refuse additional connections. Usually the inverter times out after 2 minutes.

**Comment by hoeselr** [comment]
@WillCodeForCats 

we waited 5-10 minutes with no success - then reverted to v2.2.0-pre.1 and now the integration connects to Inverter again - but no meters are shown in this Version....

![2022-08-28_18-53-50](https://user-images.githubusercontent.com/33808979/187085587-26cb9f63-d2e8-4145-bf26-b8118af50acb.jpg)

**Comment by WillCodeForCats** [comment]
Not sure on that one. I'm running pre.2 on my live and test systems and it's connecting fine.

pre.1 does not support the Multi MPPT inverters (which is what the SE82.8K is)

I can try removing the new MMPPT Events sensor.

**Comment by hoeselr** [comment]
@WillCodeForCats ok - thank you then i will try to install the new version again

**Comment by WillCodeForCats** [comment]
[Release v2.2.0-pre.3](https://github.com/WillCodeForCats/solaredge-modbus-multi/releases/tag/v2.2.0-pre.3) reverts the commits to add the new sensor and device attributes for Multi MPPT inverters.

**Comment by hoeselr** [comment]
@WillCodeForCats - now connection is up again an Meter is recognized - 
one question about the Meter : now the Meter reports a negative value to Grid (no PV Production)
shouldn't this value be in positive right now ?

![2022-08-28_19-25-19](https://user-images.githubusercontent.com/33808979/187086856-5ecf58d0-1130-410c-8df0-1fbab88085fd.jpg)

thank you very much

**Comment by WillCodeForCats** [comment]
On an Export+Import meter negative is import from grid, positive is export to grid.

**Comment by hoeselr** [comment]
@WillCodeForCats ok - thank‘s for the Info!

**Comment by hoeselr** [comment]
@WillCodeForCats if there is something that i can try on new version for MMPPT Events sensor - please let me know.

**Comment by WillCodeForCats** [comment]
I'll start with this for the v2.2.0 release and work on adding more sensors for Multi MPPT on a minor release.

**Comment by hoeselr** [comment]
@WillCodeForCats  Ok great!
